### ISSUE TITLE
Can't get past Leap mode selection dialog

### ISSUE THREAD

**Issue by BenChirlin** [leapmotion/VRCollage#24]
On Firefox Nightly 39a01 on OSX using DK2 and Leap Motion sensor mounted on HMD. Head and hand tracking both working. Can "highlight" Oculus mounted option but no way to confirm selection. Am I missing a key button or other control mechanism? If I stick my head past dialog I can sometimes see what I believe to be the photo window so I'm guessing the dialog just isn't dismissing properly.

**Comment by pehrlich** [comment]
you have to click.. but this is in no way intuitive.  I'll finish the work of removing the silly dialog.

**Comment by pehrlich** [comment]
Done.  Now the only dialog that shows is the one saying to plug in leap, which can be dismissed by.. plugging in leap.

**Comment by BenChirlin** [comment]
Thanks! I thought I had tried clicking but I might've forgotten. I'll give it a try later today.
